{% set name = "PyMarkovChain" %}
{% set version = "1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8a03fba5d9f390b528991f5e3411188b545aa16a7131cea44c5f9cf1814d08a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pymarkovchain

about:
  home: https://github.com/MaxWagner/PyMarkovChain
  license: "BEER-WARE"
  summary: 'PyMarkovChain supplies an easy-to-use implementation of a markov chain text generator.'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - asmeurer
