{% set name = "boehmgc" %}
{% set version = "8.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.hboehm.info/gc/gc_source/gc-{{ version }}.tar.gz
  sha256: 436a0ddc67b1ac0b0405b61a9675bca9e075c8156f4debd1d06f3a56c7cd289d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}

about:
  home: https://www.hboehm.info/gc/
  license: MIT
  license_family: MIT
  # https://www.hboehm.info/gc/license.txt
  license_file: license.txt
  summary: 'A garbage collector for C and C++'
  description: |
    The Boehm-Demers-Weiser conservative garbage collector can be used as a
    garbage collecting replacement for C malloc or C++ new. It allows you to
    allocate memory basically as you normally would, without explicitly
    deallocating memory that is no longer useful. The collector automatically
    recycles memory when it determines that it can no longer be otherwise
    accessed.

extra:
  recipe-maintainers:
    - asmeurer
