package:
  name: hunspell
  version: 1.4.1

source:
  git_url: https://github.com/hunspell/hunspell.git
  git_tag: v1.4.1

build:
  skip: true  # [win]
  number: 0
  has_prefix_files:
    - bin/hunspell

requirements:
  build:
    - readline
    - automake  # [linux]

  run:
    - readline

test:
  commands:
    - hunspell --help

about:
  home: http://hunspell.sourceforge.net/
  summary: Spell checker
  license: MPL 1.1/GPL 2.0/LGPL 2.1

extra:
  recipe-maintainers:
    - asmeure
