{% set major = "7.1" %}
{% set patch = "0" %}
{% set version = major + "." + patch %}

package:
    name: aspell-en
    version: {{ version }}

source:
    fn: aspell6-en-{{ major }}-{{ patch }}.tar.bz2
    url: ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-{{ major }}-{{ patch }}.tar.bz2
    sha1: d45ccda0c03e2a679c2936487ec851a1896b8150

build:
    skip: True  # [win]
    number: 0

requirements:
    build:
        - aspell
    run:
        - aspell

test:
    files:
        - test-file.txt
    commands:
        - aspell list < test-file.txt

about:
    home: ftp://ftp.gnu.org/gnu/aspell/dict/0index.html
    license: MIT and BSD-3-Clause
    summary: 'An (American, British, and Canadian) English dictionary for aspell.'

extra:
    recipe-maintainers:
        - asmeurer
