package:
  name: aspell-en
  version: 2016.06.26.0

source:
  fn: aspell6-en-2016.06.26-0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-2016.06.26-0.tar.bz2
  sha1: 64d3a6fd5ad22e63130cac94648aebdc80e55f8f

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - aspell
  run:
    - aspell

test:
  files:
    - test-file.txt
  commands:
    - aspell list < test-file.txt

about:
  home: ftp://ftp.gnu.org/gnu/aspell/dict/0index.html
  license: "Various (see Copyright file from the aspell6-en source)"
  summary: "An (American, British, and Canadian) English dictionary for aspell."

extra:
  recipe-maintainers:
    - asmeurer
