{% set ver = "0.60.7" %}
{% set date = "20110707" %}
{% set version = ver + "." + date %}
{% set fversion = ver + "-" + date %}

package:
    name: aspell
    version: {{ version }}

source:
    fn: aspell-{{ fversion }}.tar.gz
    url: ftp://alpha.gnu.org/gnu/aspell/aspell-{{ fversion }}.tar.gz
    sha1: fcd3430a03fcda27d7359d6bbbc3c1396438c183
    patches:
        # http://www.freebsd.org/cgi/query-pr.cgi?pr=180565
        - aspell.patch

build:
    number: 0
    skip: True  # [win]
    detect_binary_files_with_prefix: true

requirements:
    build:
        - perl

test:
    commands:
        - aspell --help
        # Make sure the build prefix is not hard-coded into aspell
        - if aspell dump config | grep "_build"; then exit 1; fi

about:
    home: http://aspell.net/
    license: GFDL-1.1 and LGPL-2.1 and HPND
    summary: GNU Aspell is a Free and Open Source spell checker designed to eventually replace Ispell.

extra:
    recipe-maintainers:
        - asmeurer
