package:
  name: hunspell-en
  version: 2014.02.10

source:
  url: http://extensions.openoffice.org/en/download/17707
  fn: dict-en.oxt
  sha256: 4d9692342c714e05342b29e7013f041b229a6e517f8eb44ab04d93fa1039d252

build:
  number: 0

requirements:
  run:
    - hunspell

test:
  commands:
    - echo 'test' | hunspell
    - echo 'mispellled' | hunspell

about:
  home: http://extensions.openoffice.org/en/project/english-dictionaries-apache-openoffice
  summary: "English spelling dictionaries for hunspell. Includes en_AU (Australian), en_CA (Canadian), en_GB (British), en_US (American), and en_ZA (South African)"
  license: GPL

extra:
  recipe-maintainers:
    - asmeurer
